# 5.1. Вычислите (5Е)–1, где Е – единичная матрица размера 5х5.

In [1]:
import numpy as np

In [5]:
e = np.identity(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
p = np.linalg.inv(e)
print(p)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]
