# 5.3.1. Вычислите матрицу, обратную данной:[[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [3]:
b = np.linalg.inv(a)
print(b)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [4]:
np.linalg.det(b)

0.01666666666666667

# 5.3.2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [43]:
c = np.array([[1, 2, 3, 4], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
print(c)

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
np.linalg.matrix_rank(c, 0.0001)

1