# 5.2. Вычислите определитель: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [4]:
np.linalg.det(a)

59.999999999999986