# 6.3. Сколько решений имеет линейная система: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] * X = [12, 2, 1]   

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
print(np.linalg.solve(A, B))
np.linalg.lstsq(A, B)

[ 2.83726777e+16 -5.67453553e+16  2.83726777e+16]


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


(array([-7.69444444, -0.61111111,  6.47222222]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))