# 6.4. Вычислите LU-разложение матрицы: [[1, 2, 3], [2, 16, 21], [4, 28, 73]]. После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.


In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

In [3]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
B = np.array([4, 1, 7])
np.linalg.solve(A, B)

array([ 0.50462963,  1.26157407, -0.67592593])